### ISSUE TITLE
Getting warning about incorrect peer dependency on installation

### ISSUE THREAD

**Issue by mbathke** [avenga/eslint-config#6]
we use:  `"@avenga/eslint-config": "^1.1.0"` as a dev dependency in our project. on `yarn install` i get the following warnings:

```
warning " > @avenga/eslint-config@1.1.0" has incorrect peer dependency "@typescript-eslint/eslint-plugin@~2.28.0".                               
warning " > @avenga/eslint-config@1.1.0" has incorrect peer dependency "@typescript-eslint/parser@~2.28.0".                                      
warning " > @avenga/eslint-config@1.1.0" has incorrect peer dependency "eslint-plugin-import@~2.20.2".
```

**Comment by tiborpilz** [comment]
I think the warnings are a little misleading: since it's a peer dependency, you should install the versions of those dependencies yourself to remove the warnings.

**Comment by steve-py96** [comment]
(At this point I guess I can ask :D) Why don't we just make em dependencies? I mean ofc, if I only use JS I won't need `@typescript-eslint/**` stuff, but it'd be much less of a hassle to use imo than the amount of peers I have to deal with when I need em atm (not to mention updates of the config with updated peers would be an even greater pain)
