### ISSUE TITLE
repo link on npm broken

### ISSUE THREAD

**Issue by steve-py96** [avenga/eslint-config#8]
the repo link was fixed in the `package.json` but not published apparently, it's still broken on npm

<br />

**repro:**
1. visit https://www.npmjs.com/package/@avenga/eslint-config
2. click the repo link

**Comment by frederik-b** [comment]
confirmed, working on it

**Comment by frederik-b** [comment]
apparently it is fixed in the repo but needs to be republished

**Comment by fabianmebus** [comment]
package has been republished
